SELECT distinct C.CAR_ID, C.CAR_TYPE, ROUND((C.DAILY_FEE*((100-DP.DISCOUNT_RATE)/100)),0)*30 AS "FEE"
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
LEFT JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID
JOIN (SELECT P.CAR_TYPE, P.DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    WHERE P.CAR_TYPE IN ('세단', 'SUV' ) AND P.DURATION_TYPE = '30일 이상') DP ON DP.CAR_TYPE = C.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV' ) AND  C.CAR_ID 
    NOT IN (SELECT HH.CAR_ID 
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HH
           WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC


-- 검증
# SELECT HH.CAR_ID , start_date, end_date
#             FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HH
#            WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30' 
           
-- 검증
# SELECT P.CAR_TYPE, P.DISCOUNT_RATE
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
#     WHERE P.CAR_TYPE IN ('세단', 'SUV' ) AND DURATION_TYPE = '30일 이상'
-- 세단 :8 , SUV : 5


-- 검증
# SELECT C.CAR_ID, START_DATE, END_DATE, DATEDIFF(END_DATE,START_DATE)
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
# JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID
# ORDER BY start_date