SELECT T.YEAR, T.MONTH,COUNT(DISTINCT T.USER_ID), ROUND(COUNT(DISTINCT T.USER_ID)/T.TOTAL,1)
FROM 
    (SELECT YEAR(S.SALES_DATE) AS "YEAR", MONTH(S.SALES_DATE) AS "MONTH", U.USER_ID, (SELECT count(DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = '2021') as "TOTAL"
    FROM  USER_INFO U
    LEFT JOIN ONLINE_SALE S ON U.USER_ID = S.USER_ID
    WHERE YEAR(U.JOINED) = '2021') T
WHERE T.YEAR IS NOT NULL
GROUP BY T.YEAR, T.MONTH
ORDER BY T.YEAR, T.MONTH


-- 검증
-- 2021 가입자 전체 인원
# SELECT count(DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = '2021'

-- 2021 가입자 구매 내역
# SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, GROUP_CONCAT(DISTINCT U.USER_ID)
# FROM  USER_INFO U
# LEFT JOIN ONLINE_SALE S ON U.USER_ID = S.USER_ID
# WHERE YEAR(U.JOINED) = '2021'
# GROUP BY YEAR, MONTH
# ORDER BY S.SALES_DATE

# SELECT DISTINCT U.USER_ID
# FROM  USER_INFO U
# LEFT JOIN ONLINE_SALE S ON U.USER_ID = S.USER_ID
# WHERE YEAR(U.JOINED) = '2021' AND MONTH(S.SALES_DATE) = 3
# ORDER BY S.SALES_DATE
