SELECT CONCAT_WS('/','/home/grep/src',F.BOARD_ID, CONCAT(F.FILE_ID,F.FILE_NAME,F.FILE_EXT))
FROM USED_GOODS_FILE F
WHERE F.BOARD_ID = (SELECT B.BOARD_ID
                    FROM USED_GOODS_BOARD B
                    ORDER BY B.VIEWS DESC
                    LIMIT 1)
ORDER BY F.FILE_ID DESC

