SELECT CATEGORY, PRICE MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) in
    (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    )
AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY 2 DESC


-- 검증
# SELECT *
# FROM FOOD_PRODUCT
# WHERE CATEGORY IN ( '과자', '국', '김치', '식용유')
# ORDER BY PRICE DESC
# 김치 19000 CD_KC00001
# 식용유 8950 CD_OL00004
# 국 2900 CD_SU00004
# 과자 1950 CD_CK00003