SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(PRICE*SALES) AS "TOTAL_SALES"
FROM BOOK_SALES S
JOIN BOOK B ON B.BOOK_ID = S.BOOK_ID
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE S.SALES_DATE LIKE '2022-01-%'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC


-- 검증
# SELECT *
# FROM BOOK_SALES S
# JOIN BOOK B ON B.BOOK_ID = S.BOOK_ID
# JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
# WHERE S.SALES_DATE LIKE '2022-01-%'
# ORDER BY A.AUTHOR_ID, B.CATEGORY

-- 김수진 생활
# (1+3+9+8+9+7+10+10+10+10+4+5) * 9500 =817000

